= Rapport d’avancement du groupe 1.1
PACT groupe 11
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « Swypeek »

=== Membres du groupe

* Rita Abubaker
* Zachary Abessera
* Jules Dany 
* Laurent Chhy
* Abdelali Boukhari
* Olivia Hennequin
* Mehdi Bentaleb
* Aurélien Castre

=== Tuteur

* Giovanna Varni

=== Encadrant génie logiciel

* Jean-Claude Dufourd

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*

Décrire votre projet sans le scénariser : De quoi s’agit-il ? En quoi
cette idée est compatible avec le thème de PACT ? Qu’est ce qu’il
permettrait de faire de façon générale.

== English Summary (PAN1)

*_Note : 15 lignes max, version anglaise du texte précédent_*

[.text-justify]
_Swypeek_ is a convenient application which allows a group of people to *decide on a movie to watch*. The selection is done through a practical and intuitive interface, making sure the movie chosen pleases everyone.

[.text-justify]
The picking process is based on the simple *swipe mechanism*. In the case of a small group, a movie is simultaneously presented to all of the party participants, along with a small description and a trailer. Each person will then either swipe right if they feel enthusiastic about watching the movie, or left otherwise. As soon as everyone will have finished swiping the movie, another one will be suggested. The movie will be determined by unanimity. The movies displayed are selected by the application according to the user profiles, their preferences, and their tendencies. 
On the other hand, if their is a lot of users, the application will select a certain number of movies using their profiles. The users will be presented with two movies at a time and will have to swipe towards their favorite. The application then creates a sorted list of preference for each user and finally the movie is selected based on an accurate electoral system.

[.text-justify]
The group of people can either be precomposed, or formed online in the application by bringing together individuals who belong to the same institution (a school for example). To help allow these encounters, the app will contain a multi-communal social media feature centered around movie culture. _Swypeek_ can be used in two mods: a face to face mod and a distance mod. In the latter, users will have the option to link their profile to their streaming platform in order to synchronize their movie player with the other group members.

[.text-justify]
_Swypeek_ serves people by helping them decide and giving each member of the group a chance to participate in the choice. Moreover, in these times of hardship, it can be nice to have distant movie nights with friends and even meet new people who share the same passion through the application.

*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autre:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
differents fichiers) se trouve dans le fichier courant.

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
