=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

[.text-justify]
À une époque où les gens sont si souvent séparés, se connecter sur Internet avec ses amis, sa famille et ses partenaires à distance est devenu une nécessité. Quel meilleur moyen de passer un moment réconfortant que de regarder des films ensemble ? En fait, cette demande est devenue tellement populaire que de nombreuses personnes ont sauté sur l'occasion pour créer des applications, des sites web et des logiciels qui permettent aux gens de reproduire autant que possible une soirée cinéma.

[.text-justify]
Bien qu'ayant le même objectif, ces solutions se sont avérées relativement différentes et chacune d'entre elles a ses avantages et ses inconvénients. Par exemple, il existe des sites web tels que <<TwoSeven>> et <<Kastapp>> qui permettent aux utilisateurs de créer des soirées ou des _salles virtuelles_ et de regarder du contenu avec des amis. Les deux permettent la capture vidéo et d'écran et fonctionnent avec de nombreuses plateformes de streaming. Cependant, pour _Kast_, la capacité de la salle est limitée à 100 personnes et la qualité est généralement faible, sauf si les utilisateurs paient pour un abonnement premium. Dans le même thème, il y a <<NetflixParty>> mais c'est limité à _Netflix_.
Parmi ceux-ci, _two-seven_ est le seul qui offre une fonction de synchronisation, ce qui peut être très utile. Cette fonctionnalité est l'objectif principal du logiciel _open source_ <<SyncPlay>> qui permet aux utilisateurs de synchroniser leurs lecteurs multimédia afin de pouvoir regarder des vidéos ensemble. Cependant, ils doivent posséder une copie du média à lire, ce qui n'est pas utile pour la diffusion de vidéos en _streaming_.

[.text-justify]
Si les options précédentes permettent aux gens de regarder ensemble du contenu sur internet, elles ne facilitent pas leur choix, lequel peut être difficile lorsque les gens ont des goûts différent. C'est cette problématique qui constitue l'objectif principal de notre application. Par ailleurs, <<DNM>> est un site web qui combine le choix de deux personnes et propose une alternative qui est censée les satisfaire. Cependant, il est limité à deux films seulement. Il existe d'autres applications qui aident à choisir des films mais elles sont limitées au gôut d’une seule personne (<<Fixee>> ou <<Itcher>>). 

[.text-justify]
Pour faciliter le choix des films, les gens s'inspirent généralement des réseaux sociaux centrés sur le cinéma où les gens partagent leur classement et leurs critiques sur différents films, populaires ou non. Le site web le plus fourni pour les films est <<IMDB>>.  Il existe d'autres sites web qui disposent de différents systèmes de classification, comme <<FilmCrave>>. Récemment, c'est le site <<Letterboxd>> qui a été le plus utilisé et qui a gagné le plus en popularité.

[.text-justify]
Comme vous l'avez peut-être remarqué, ces applications et sites web ne résolvent qu'une partie du problème à la fois. Quand les uns ont des interfaces peu intuitives, les autres sont extrêmement complexes. C'est pourquoi nous avons décidé de créer une application qui intègre non seulement toutes ces fonctionnalités à la fois, mais qui se veut aussi simple et intuitive pour être utilisée par tout le monde.

