=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

À une époque où les gens sont si facilement séparés, se connecter sur Internet avec ses amis, sa famille et ses partenaires à distance est devenu une nécessité. Quel meilleur moyen de passer un moment réconfortant que de regarder des films ensemble ? En fait, cette demande est devenue tellement populaire que de nombreuses personnes ont sauté sur l'occasion pour créer des applications, des sites web et des logiciels qui permettent aux gens de reproduire autant que possible une soirée cinéma.  

Bien qu'ayant le même objectif, ces solutions se sont avérées relativement différentes et chacune d'entre elles a ses avantages et ses inconvénients. Par exemple, il existe des sites web tels que <<TwoSeven>> et <<Kastapp>> qui permettent aux utilisateurs de créer des soirées ou des "salles virtuelles" et de regarder du contenu avec des amis. Les deux permettent la capture vidéo et d'écran et fonctionnent avec de nombreuses plateformes de streaming. Cependant, pour Kast, la capacité de la salle est limitée à 100 personnes et la qualité est généralement faible, sauf si les utilisateurs paient pour un abonnement Premium. Dans le même thème, il y a <<NetflixParty>> mais c'est limité à Netflix.
 Parmi ceux-ci, two-seven est le seul qui offre une fonction de synchronisation, ce qui peut être très utile. Cette fonctionnalité est l'objectif principal du logiciel Open source <<SyncPlay>> qui permet aux utilisateurs de synchroniser leurs lecteurs multimédia afin de pouvoir regarder des vidéos ensemble. Cependant, ils doivent posséder une copie du média à lire, ce qui n'est pas utile pour la diffusion de vidéos en Streaming.

Si ces options précédentes permettent aux gens de regarder ensemble du contenu sur internet, elles ne facilitent pas leur choix, ce qui peut être difficile lorsque les gens ont des goûts différents, notamment pour les films, problématique qui constitue l'objectif principal de notre application. Par ailleurs, <<DNM>> est un site web qui combine le choix de deux personnes et propose une alternative qui est censée les satisfaire. Cependant, il est limité à deux films seulement. Il existe d'autres applications qui aident à choisir des films mais elles sont limitées au gôut d’une seule personne (<<Fixee>> 
  ou <<Itcher>>). 

Pour faciliter le choix des films, les gens s'inspirent généralement des réseaux sociaux centrés sur le cinéma où les gens partagent leur classement et leurs critiques sur différents films, populaires ou non. Le site web le plus fourni pour les films est <<IMDB>>.  Il existe d'autres sites web qui disposent de différents systèmes de classification, comme <<FilmCrave>>. Récemment, c'est le site <<Letterboxd>> qui a été le plus utilisé et qui a gagné le plus en termes de popularité.

Comme vous l'avez peut-être remarqué, ces applications et sites web ne résolvent qu'une partie du problème à la fois. Certains ont des interfaces difficiles et d'autres sont extrêmement compliqués à comprendre. C'est pourquoi nous avons décidé de créer une application qui non seulement permet toutes ces fonctionnalités à la fois, mais nous avons également décidé de garder son fonctionnement relativement simple et intuitif afin qu'il soit apprécié et compris par tout le monde.

